### ISSUE TITLE
Links with backticks

### ISSUE THREAD

**Issue by tsiq-karold** [twosigma/znai#172]
MDoc displays links with backticks as follows:
![screenshot 2018-12-20 at 15 00 01](https://user-images.githubusercontent.com/33879397/50292050-0c3dd700-0468-11e9-9734-12f156bb87f1.png)

I think the way IntelliJ displays them is actually nicer:
![screenshot 2018-12-20 at 15 00 08](https://user-images.githubusercontent.com/33879397/50292064-14961200-0468-11e9-8535-c01859502294.png)

Could we consider restyling this?  The main difference is the underline vs. different background as the highlighting mechanism.

In case it helps, this is the MD that generated the screenshots above:
```
[test link with `backticks`](chapter/page)
```

**Comment by MykolaGolubyev** [comment]
@jyeakel I think we still need to preserve link color and underscore (in case of light theme). What do you think?

**Comment by jyeakel** [comment]
I think links should have consistent underline and coloring, though it makes sense for the backticked portion of the text to be monospaced. What's bothersome about the screenshots to me is that the backticked portion is underline even though we don't use underlines on links in the dark mode. We should fix that.
