### ISSUE TITLE
Global search index xml root node rename and coordination

### ISSUE THREAD

**Issue by MykolaGolubyev** [twosigma/znai#262]
Znai generates search index xml file with `mdoc` as a root node. There is already Coveo Enterprise Search crawler that expects a certain xml path. 

@jyeakel we will need to coordinate the final renames. Could you please check if you can setup Coveo crawler to handle both root nodes: `mdoc` and `znai`?

**Comment by jyeakel** [comment]
This is already done. Our crawler should support both.
