### ISSUE TITLE
Trying to highlight a string that doesn't exist in the snippet breaks at runtime

### ISSUE THREAD

**Issue by blevz** [twosigma/znai#268]
When you use :include-file: with a {highlight:"some string"} annotation if the string doesn't appear in the included file the entire page that the include-file is a part of will fail to render with this error:
`react-dom.min.js:103 Error: none of the lines matches specified highlights:`

This would be helpful if this were a build time error but because it happens at runtime it makes it easy to accidentally break documentation when you edit the code but forget to update the highlight string

**Comment by MykolaGolubyev** [comment]
Oh, that is definitely not the intended behavior :(
