### ISSUE TITLE
Landing page should indicate when documentation doesn't exist

### ISSUE THREAD

**Issue by jyeakel** [twosigma/znai#271]
If documentation doesn't exist, users sit on the "preparing ... documentation" screen indefinitely with the message "checking documentation cache".

If the documentation does not exist in the cache, after some timeout the user should receive that message.

**Comment by MykolaGolubyev** [comment]
If I remember correctly there are all the necessary extension points available and it could be the internal implementation of those in not handling sending the right message correctly.

**Comment by jyeakel** [comment]
As suggested, we made the necessary internal changes to handle this issue.
