### ISSUE TITLE
Provide option for client side routing

### ISSUE THREAD

**Issue by tsiq-karold** [twosigma/znai#272]
Right now, we generally rely on the web server mapping a path in znai, such as `id/chapter/page`, to the index.html in that directory.  Not all web servers will do that by default.  It would be useful to provide an option which uses client side routing (i.e. react style paths like `id#/chapter/page`.

**Comment by MykolaGolubyev** [comment]
That will not be that trivial as we physically generate different html files. 
How about ‘chapter/page.html’ option?

Do you have an example of a server that won’t redirect to ‘index.html’

**Comment by tsiq-karold** [comment]
I think `chapter/page.html` would probably work, the main requirement really is to be able to share a link (by copying it out of the browser) and have that link open without needing the browser to perform any redirection.

In my case, the generated docs are hosted in AWS S3 and served up via CloudFront.  However, in discussing this problem with other folks here they tell me other web server have the same behaviour but no specific examples were given.

**Comment by MykolaGolubyev** [comment]
Is the problem that S3 + CloudFront don't do a proper redirect or is there an auth layer that is failing to re-auth?

**Comment by tsiq-karold** [comment]
Hmmm, it's not re-auth but whether it's the S3+CF or the auth component that's guilty of this behaviour I'm not sure.  What actually happens is that opening `id/chapter/page` redirects to `id` and loads the `index.html` in there.

**Comment by MykolaGolubyev** [comment]
I am not expert in that stack, but just wanted to confirm/understand if that is not a miss-configuration on the stack side as I didn't experience that behavior anywhere else.

**Comment by MykolaGolubyev** [comment]
@tsiq-karold checking just in case if there were any changes around this. I don't have a simple enough solution on page gen side.

**Comment by tsiq-karold** [comment]
We found a solution on our end.

**Comment by MykolaGolubyev** [comment]
Is solution shareable?

**Comment by tsiq-karold** [comment]
The part of the stack that was responsible for the redirect in this case was written by us so we updated it to work correctly with the pages that znai generates.
