### ISSUE TITLE
Preview does not handle jsons with null values

### ISSUE THREAD

**Issue by tsiq-karold** [twosigma/znai#277]
Opening the preview docs results in this error in the browser:
```
react-dom.min.js:103 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at e.value (main.js:1)
    at e.value (main.js:1)
    at main.js:1
    at Array.forEach (<anonymous>)
    at e.value (main.js:1)
    at e.value (main.js:1)
    at e.value (main.js:1)
    at a (main.js:1)
    at t.value (main.js:1)
```

**Comment by jyeakel** [comment]
Additionally (though maybe this should be handled as a separate ticket) it looks like JSON functionality breaks on non-ASCII characters: `SyntaxError: Unexpected token ü in JSON at position 256`

**Comment by MykolaGolubyev** [comment]
@jyeakel could you please attach a minimal Unicode example that reproduce it?

**Comment by jyeakel** [comment]
Disregard the ASCII comment. This appears to be caused from a typo elswhere in the JSON file.
