### ISSUE TITLE
:include-json: and :include-rest-test: break if json field has null value

### ISSUE THREAD

**Issue by jyeakel** [twosigma/znai#305]
If JSON has a null value (i.e., {"key": null}) the browser will load a blank screen for the documentation page and the dev console will display:

`TypeError: Cannot convert undefined or null to object`

**Comment by tsiq-karold** [comment]
Is this a dupe of https://github.com/twosigma/znai/issues/277?

**Comment by jyeakel** [comment]
Looks like it may be. Is the issue only limited to previews? Our internal reporter also noted that non-ASCII characters also create issues: `SyntaxError: Unexpected token ü in JSON at position 256`

**Comment by jyeakel** [comment]
Closing as duplicate will add comments to other issue.

**Comment by tsiq-karold** [comment]
No, it’s not, I forgot to update the issue but it also impacts build, not just preview.
