### ISSUE TITLE
Add support link in documentation

### ISSUE THREAD

**Issue by jyeakel** [twosigma/znai#323]
For the time being, we've decided to more narrowly address the use cases originally intended to be handled with #292. We want to provide a simple mechanism for documentation authors to optionally specify and display a support link in their documentation. This link would be provided in configuration.

I'm suggesting we add this as a link reading "Support" at the top of the page under the title (see screenshot)

![image001 (1)](https://user-images.githubusercontent.com/4038956/70178860-fd692800-16aa-11ea-9f76-b9cb1fdba8c1.png)

**Comment by MykolaGolubyev** [comment]
I like the simplification aspect of it!
I thought initially to use footer for this kind of things.

**Comment by jyeakel** [comment]
As the footer is optional and completely customizable in both content and layout, I figured it was more straightforward to handle the link elsewhere. Additionally, while I know footers are a common place for contact links, pages can be arbitrarily long so it seems like a good idea to make the contact option easily reachable for any possible page a user lands on.
