### ISSUE TITLE
New change highlighting in preview not behaving correctly

### ISSUE THREAD

**Issue by jyeakel** [twosigma/znai#375]
The new highlighting feature is awesome and worked almost everywhere I tested it but for some reason when testing changes to the rationale.md file when I made changes it jumped to the middle of the page no matter where the change occurred.

**Comment by MykolaGolubyev** [comment]
Please check if you have url anchored with `#section-name`

**Comment by jyeakel** [comment]
There isn't a section name anchor in rationale.md, but I am no longer able to produce the issue. Perhaps this can be closed then?

**Comment by MykolaGolubyev** [comment]
were you
